### ISSUE TITLE
sample中的部分gradle依赖过期

### ISSUE THREAD

**Issue by vitaviva** [huaweicodelabs/harmonyos-codelabs#1]
以`ShoppingJs`为例（0cfa8d6），不少gradle依赖都找不到，导致无法通过编译，替换为IDE模板工程中依赖版本后可以编译通过。

<img width="423" alt="Screen Shot 2021-04-18 at 12 19 02 PM" src="https://user-images.githubusercontent.com/6120268/115134148-4f141780-a040-11eb-9132-702f482c918b.png">
<img width="518" alt="Screen Shot 2021-04-18 at 12 19 08 PM" src="https://user-images.githubusercontent.com/6120268/115134149-50dddb00-a040-11eb-99f9-3251d85fef28.png">

我的IDE：
![Screen Shot 2021-04-18 at 12 14 37 PM](https://user-images.githubusercontent.com/6120268/115134094-ed53ad80-a03f-11eb-953e-b2b323c30919.png)

**Comment by xuzizi** [comment]
已更新~

另外，使用最新版本IDE会自动修复该问题~
