### ISSUE TITLE
跑个demo都要注册提交信息审核？才能签名？

### ISSUE THREAD

**Issue by feixiao** [huaweicodelabs/harmonyos-codelabs#10]

**Comment by feixiao** [comment]
跑个demo都要注册提交信息审核？才能签名？

**Comment by xuzizi** [comment]
真机需要签名，模拟器不用签名

**Comment by xuzizi** [comment]
请参考官方文档 https://developer.harmonyos.com/cn/docs/documentation/doc-guides/ide_debug_device-0000001053822404
