### ISSUE TITLE
App签名还要改包名？

### ISSUE THREAD

**Issue by feixiao** [huaweicodelabs/harmonyos-codelabs#11]
我只是想简单真机运行效果，发现签名需要包名....也就是说我还需要改包名？

![image](https://user-images.githubusercontent.com/5179380/125375544-ce08ba00-e3bb-11eb-9f27-e74b7b814fdd.png)

**Comment by xuzizi** [comment]
对，在真机上运行，需要使用自己的包名，修改config.json中的bandlename字段就行。
详情参见官网文档：https://developer.harmonyos.com/cn/docs/documentation/doc-guides/build_hap-0000001053342418#section7901222142216
