### ISSUE TITLE
分布式邮件编辑问题：为什么运行起来后，选中设备后也无法跨设备调度成功

### ISSUE THREAD

**Issue by CNTcnt** [huaweicodelabs/harmonyos-codelabs#4]
为什么运行起来后，可以检索到设备，选中设备后也无法跨设备调度成功，我有同账号，跟在同一个局域网中，也有打开多设备协同，也给了权限，为什么不管第二个设备有没有安装，就是无法调度起来。是怎么回事，log中也没有看出报什么错，请尽快处理，至少官方demo要跑的起来啊。
06-03 16:54:11.792 19946-19946/com.huawei.maildemo_my W wei.maildemo_m: Can't mmap dex file /data/app/com.huawei.maildemo_my-SyWv_ptJvxLSv_Jon7-G0A==/base.apk!classes.dex directly; please zipalign to 4 bytes. Falling back to extracting file.
06-03 16:54:11.795 19946-19946/com.huawei.maildemo_my W wei.maildemo_m: JIT profile information will not be recorded: profile file does not exits.
06-03 16:54:11.801 19946-20425/com.huawei.maildemo_my I HwPartIawareFactory: add android.common.HwPartIawareFactoryImpl to memory.
06-03 16:54:11.746 19946-19946/? I wei.maildemo_m: Late-enabling -Xcheck:jni
06-03 16:54:11.765 19946-19946/? E libc    : Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
06-03 16:54:11.765 19946-19946/? E wei.maildemo_m: LoadAppImageStartupCache enabled : 1
06-03 16:54:11.765 19946-19946/? E wei.maildemo_m: Unknown bits set in runtime_flags: 0x8000
06-03 16:54:11.759 19946-19946/? W wei.maildemo_m: type=1400 audit(0.0:2485): avc: denied { read } for pid=19946 name="u:object_r:device_config_runtime_native_prop:s0" dev="tmpfs" ino=17125 scontext=u:r:untrusted_app:s0:c199,c256,c512,c768 tcontext=u:object_r:device_config_runtime_native_prop:s0 tclass=file permissive=0
06-03 16:54:11.766 19946-19946/? I wei.maildemo_m: Reinit property: dalvik.vm.checkjni= false
06-03 16:54:11.766 19946-19946/com.huawei.maildemo_my I wei.maildemo_m: ReInitProperties: persist.vm.debug.dumpapi= false
06-03 16:54:11.806 19946-20422/com.huawei.maildemo_my I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.huawei.maildemo_my#10199#256
06-03 16:54:11.806 19946-20422/com.huawei.maildemo_my I HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=0 newCnt=1
06-03 16:54:11.808 19946-19946/com.huawei.maildemo_my E 01510/IPCJni: IPCAdapter enter
06-03 16:54:11.810 19946-20422/com.huawei.maildemo_my I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.huawei.maildemo_my#10199#0

**Comment by xuzizi** [comment]
测试了一下没有问题，请问是使用的最新正式版本的IDE和最新代码吗

**Comment by CNTcnt** [comment]
感谢恢复，代码没有问题，忘记来更新状态了，我一开始的账号不行，然后我换了账号，就可以了，我也不知道怎么回事，还有，我想问几个问题：
我想要咨询几个问题；

目前我有两台真机，在测试迁移时，不管我怎么设备，只有两台手机登陆了同个华为账号才可以找寻到设备，我是根据官网教程里面，通过流转任务管理服务，来找寻设备，代码如下所示，跟官网的教程代码。我也没有指定一定要同个账号，但是就是搜索不到其他设备；请问是怎么回事。然后就算是同个账号，我在系统的超级终端里面也没有看到我的另一台设备，只能从应用里面搜索到再操作。



ExtraParams params = ExtraParams()String[] devTypes = String[]{ExtraParams.ExtraParams.}params.setDevType(devTypes)String jsonParams = params.setJsonParams(jsonParams).register(params)
官网里面的  系统推荐流转  这个该怎么触发，我只有在另一个手机上登陆同一个账号时，第一个手机上就会弹出系统的通知，说可以流转到我第二个设备，然后后面不管我是关闭应用再重启，还是直接重装，都触发不了了，请问是代码哪里需要注意的吗？

还有一个问题，原子化服务现在的上传入口怎么没有找寻到。我在那个AppGallery Connect 里面也没有找到入口，请问我该怎么测试。是现在还没有开放这个功能吗？
