### ISSUE TITLE
config.json配置有误

### ISSUE THREAD

**Issue by trysingtime** [huaweicodelabs/harmonyos-codelabs#6]
时间: 20210609
问题: harmonyos-codelabs/DistributedMail/entry/src/main/config.json配置有误, 无法成功编译
修改: "module"."abilities"."formEnabled" -> "module"."abilities"."formsEnabled"

**Comment by xuzizi** [comment]
因IDE升级导致，我们即将批量修复~ 谢谢

**Comment by xuzizi** [comment]
已全部修改
