### ISSUE TITLE
#: only 1 subschema matches out of 2

### ISSUE THREAD

**Issue by chengxuyuan12345** [huaweicodelabs/harmonyos-codelabs#8]
这个报错是什么原因

**Comment by xuzizi** [comment]
请问是哪个项目，可以详细描述一下吗

**Comment by xuzizi** [comment]
收到收到a

**Comment by chengxuyuan12345** [comment]
> 请问是哪个项目，可以详细描述一下吗

分布式亲子教育

**Comment by chengxuyuan12345** [comment]
> > 请问是哪个项目，可以详细描述一下吗
> 
> 分布式亲子教育

我直接clone下来跑就报这个错

**Comment by xuzizi** [comment]
请问使用的什么版本的IDE和sdk呢，我们测试没有发现这个问题。
建议使用最新版本IDE，同时把sdk中的版本和toolchains升级到最新，以避免配套问题
