### ISSUE TITLE
This device type does not match the project profile. Error while Deploying HAP

### ISSUE THREAD

**Issue by feixiao** [huaweicodelabs/harmonyos-codelabs#9]
No config.json file can been found!

**Comment by xuzizi** [comment]
This problem may be caused by you choosing the wrong simulator type, or you can change the config.json file in the project folder / SRC / main to change the "devicetype" field to the corresponding device type, such as "car", "phone", "tablet", etc.

**Comment by xuzizi** [comment]
if you're using the latest Deveco , the "devicetype" field cannot be "defalut". We have just fix this problem. Please update the codes.
